name: ✨ Feature Request
description: Suggest an idea for LiminalQA
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request
        We'd love to hear your ideas! 💡

  - type: textarea
    id: problem
    attributes:
      label: 🤔 Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: What other solutions have you thought about?

  - type: dropdown
    id: priority
    attributes:
      label: ⚡ Priority
      options:
        - Low (Nice to have)
        - Medium (Would improve workflow)
        - High (Blocking current work)
        - Critical (Cannot use product without this)
    validations:
      required: true

  - type: checkboxes
    id: willingness
    attributes:
      label: 🙋 Willingness to Contribute
      options:
        - label: I'm willing to implement this feature myself
        - label: I can help with testing
        - label: I can help with documentation
